# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c51bdbb1e7eb10062bfbcd082cd6c194dd37e0b66ebed927d26f74ce04c70ce03699ab247ed19dd5de6701a596c9bdc063bcc3a1535bf8c6aff21b88078878f5

test:
  secret_key_base: d92f8a8f34175365edba121e9a0751ddb3fdcc0ce73495456bb466b3e3b324139a2ad1923754b53692080711c4c10b34afe76ca8eba78dcb2e02268e11cb7cc3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
